### ISSUE TITLE
compile fails with {:error, :no_beam_info} with elixir 1.10

### ISSUE THREAD

**Issue by dgulinobw** [Supersonido/rebar_mix#16]
`mix new rebar_mix_test`

rebar_mix_test$ cat rebar.config 
```
{erl_opts, [debug_info]}.
{deps, [
        {jason, "1.2.0"}
       ]}.

{shell, [
    {apps, [rebar_mix_test]}
]}.

{plugins, [rebar_mix]}.
{provider_hooks, [
  {pre,  [{compile, {mix, find_elixir_libs}}]},
  {post, [{compile, {mix, consolidate_protocols}}]}
]}.
```

rebar_mix_test$ ./rebar3 shell
```
===> Verifying dependencies...
===> Fetching jason v1.2.0
===> Version cached at /home/dog/.cache/rebar3/hex/hexpm/packages/jason-1.2.0.tar is up to date, reusing it
===> Fetching decimal v1.8.1
===> Version cached at /home/dog/.cache/rebar3/hex/hexpm/packages/decimal-1.8.1.tar is up to date, reusing it
===> Compiling decimal
Compiling 1 file (.ex)
Generated decimal app
===> Compiling jason
Compiling 8 files (.ex)
Generated jason app
===> Compiling rebar_mix_test
Consolidating 13 implementations of protocol Elixir.Jason.Encoder
** (MatchError) no match of right hand side value: {:error, :no_beam_info}
    rebar_mix_protocol_consolidation.exs:14: anonymous fn/3 in :elixir_compiler_0.__FILE__/1
    (elixir 1.10.2) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:783: Enum.each/2
    (elixir 1.10.2) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:783: Enum.each/2
===> Unable to run post hooks for 'compile', command 'elixir_script_failed' in namespace 'rebar_mix_hook' not found.


This error happens with elixir 1.10.2.  Works with elixir 1.9.4
```
$ iex
```
Erlang/OTP 21 [erts-10.3.5.10] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
```

./rebar3 --version
`rebar 3.13.1 on Erlang/OTP 21 Erts 10.3.5.10`

**Comment by dgulinobw** [comment]
No error with elixir 1.9.4:
`$ export PATH=/opt/elixir-1.9.4/bin/:$PATH    `                   

rebar_mix_test$ ./rebar3 shell                                                 
```

===> Verifying dependencies...
===> Compiling rebar_mix_test
Erlang/OTP 21 [erts-10.3.5.10] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.3.5.10  (abort with ^G)
1> ===> The rebar3 shell is a development tool; to deploy applications in production, consider using releases (http://www.rebar3.org/docs/releases)
===> Booted rebar_mix_test
1> 
```

**Comment by dgulinobw** [comment]
But with elixir 1.9.4, doesn't create consolidated directory to include elixir .beam:

rebar_mix_test$ ./rebar3 release

```
===> Verifying dependencies...
===> Compiling rebar_mix_test
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /opt/elixir-1.9.4/bin/../lib/elixir/../eex/ebin
          /opt/elixir-1.9.4/bin/../lib/elixir/../elixir/ebin
          /opt/elixir-1.9.4/bin/../lib/elixir/../ex_unit/ebin
          /opt/elixir-1.9.4/bin/../lib/elixir/../iex/ebin
          /opt/elixir-1.9.4/bin/../lib/elixir/../logger/ebin
          /opt/elixir-1.9.4/bin/../lib/elixir/../mix/ebin
          /opt/rebar_mix_test/_build/default/lib
          /usr/lib/erlang/lib
===> Resolved rebar_mix_test-0.1
===> Including Erts from /usr/lib/erlang
===> release successfully created!
===> Unable to copy from /opt/rebar_mix_test/_build/default/consolidated to /opt/rebar_mix_test/_build/default/rel/rebar_mix_test/releases/0.1/consolidated because of {copy_failed,
                                                                                                                                                                   enoent}

```
rebar_mix_test$ ls -latr _build/default/rel/rebar_mix_test/releases/0.1/
```
total 48
-rw-rw-r-- 1 dog dog  140 Apr 10 15:05 rebar_mix_test.rel
-rw-rw-r-- 1 dog dog  977 Apr 10 15:05 vm.args
-rw-rw-r-- 1 dog dog  394 Apr 10 15:05 sys.config
-rw-rw-r-- 1 dog dog 8594 Apr 10 15:05 rebar_mix_test.script
-rw-rw-r-- 1 dog dog 7191 Apr 10 15:05 rebar_mix_test.boot
drwxrwxr-x 1 dog dog   50 Apr 10 15:05 ..
-rw-rw-r-- 1 dog dog 6753 Apr 10 15:05 no_dot_erlang.boot
-rw-rw-r-- 1 dog dog 6753 Apr 10 15:05 start_clean.boot
drwxrwxr-x 1 dog dog  218 Apr 10 15:05 .
```

rebar_mix_test$ cat rebar.config 
```
{erl_opts, [debug_info]}.
{deps, [
        {jason, "1.2.0"}
       ]}.

{shell, [
    {apps, [rebar_mix_test]}
]}.

{plugins, [rebar_mix]}.
{provider_hooks, [
  {pre,  [{compile, {mix, find_elixir_libs}}]},
  {post, [{compile, {mix, consolidate_protocols}}]}
]}.

{relx, [
        {release, 
            {rebar_mix_test, "0.1" %% git hash
        },
            [rebar_mix_test]
        },
        {overlay, [
                {copy, "{{base_dir}}/consolidated", "releases/{{release_version}}/consolidated"}
        ]}
       ]
}.
```

**Comment by dgulinobw** [comment]
Tested, see same issues with elixir 1.10 and 1.9 running on erlang 22.3.2:
. /home/dog/.asdf/installs/erlang/22.3.2/activate

**Comment by spokc** [comment]
Having this issue too. Any updates ?

**Comment by spokc** [comment]
@tsloughter Do we know what's happening here ? What steps can we take to address with latest Elixir distribution ?

**Comment by tsloughter** [comment]
I don't and have no time to really work on this. We need to find someone else who can help with this plugin as I will not really be around for the coming weeks or months.

@Supersonido ?

**Comment by Supersonido** [comment]
> I don't and have no time to really work on this. We need to find someone else who can help with this plugin as I will not really be around for the coming weeks or months.
> 
> @Supersonido ?

I'll take care of the library

**Comment by spokc** [comment]
@Supersonido Great!! Would you be able to take a look at this ?

**Comment by spokc** [comment]
@Supersonido Did you get time to check this ?

**Comment by auror** [comment]
Any updates here ?

**Comment by spokc** [comment]
Any updates here ?

**Comment by Supersonido** [comment]
Hi, sorry for the delay
Can you try using what I did on the branch: `feature/merge`. If works, I would move it into master as soon as a I remove a warning that shows during the release process.

**Comment by spokc** [comment]
@Supersonido Thanks. On it

**Comment by spokc** [comment]
@Supersonido there's an error during compilation
```
===> Unable to run pre hooks for 'compile', command 'find_elixir_libs' in namespace 'mix' not found.
```

**Comment by Supersonido** [comment]
Remove the library hooks.

**Comment by spokc** [comment]
Yeah @Supersonido It works! 🖖🏻
